return {
  "romus204/tree-sitter-manager.nvim",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    require("tree-sitter-manager").setup({
      ensure_installed = {
        "json",
        "jsonc",
        "javascript",
        "typescript",
        "tsx",
        "yaml",
        "toml",
        "html",
        "css",
        "markdown",
        "markdown_inline",
        "latex",
        "svelte",
        "graphql",
        "bash",
        "lua",
        "vim",
        "vimdoc",
        "dockerfile",
        "gitignore",
        "query",
        "regex",
        "comment",
        "c",
        "rust",
        "go",
        "gomod",
        "gowork",
        "gosum",
        "python",
        "terraform",
        "hcl",
      },
      highlight = true,
      auto_install = true,
    })
  end,
}
